### ISSUE TITLE
o-colors v2.5 and v3 compatibility

### ISSUE THREAD

**Issue by kaelig** [callumlocke/origami-product-boilerplate#13]
`o-colors` v2.5 and v3 include fixes for LibSass compatibility.

Not sure what would happen using these two versions of o-colors and how the `color()` function of this boilerplate. If you need assistance testing I'll be happy to help.

Testing steps:
1. Put `"o-colors": ">=2.5.0 <4` in bower.json
2. `bower i`
3. then test the project compiles well with quoted values `el { color: color('red'); }`
4. `bower i o-colors@3`
5. compile again

Note that all `color()` calls should be made with quoted values, because Sass thinks `red` is a color, whereas `'red'` is a string.
- Good: `color('red')`
- Bad: `color(red)`

---
- [ ] Sync [list of colors](https://github.com/callumlocke/origami-product-boilerplate/blob/master/client/styles/_functions.scss#L7) with o-colors v3
- [x] Make the boilerplate compatible with o-colors v2.5 and v3
- [x] Test with OBT v3 (still in beta when writing this)

**Comment by callumlocke** [comment]
I've removed custom color function now, so not an issue

**Comment by callumlocke** [comment]
thanks for this!
